import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useTranslation } from "next-i18next";
import nextI18nConfig from "../../next-i18next.config.mjs";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import { api } from "~/utils/api";

import Box from "~/components/Box.tsx";

export const getServerSideProps: GetServerSideProps = async (ctx) => ({
  props: {
    ...(await serverSideTranslations(
      ctx.locale as string,
      ["common"],
      nextI18nConfig,
      ["de"]
    )),
  },
});

const Home: NextPage = () => {
  const { t } = useTranslation("common");
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  console.log(hello.data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{t("title")}</h1>
        <Box />
      </main>
    </>
  );
};

export default Home;
